### ISSUE TITLE
[NODES] Hunting Quest VI Nodes(Assumes Radiant Hand always appears on Wave 3)

### ISSUE THREAD

**Issue by SkyRider13** [gakiloroth/gakiloroth.github.io#13]
Decided to add the Future Hunting Quest node for NA

W3sibmFtZSI6IkN1cnNlZCBCZWFzdCBHYWxsc3RvbmUgYW5kIEFycm93aGVhZCBvZiBEaXNhc3Rlcm91cyBTaW46IEdpYW50IERlbW9uIEJvYXIgSHVudCBRdWVzdCAoSHVudGluZyBRdWVzdCBQYXJ0IFZJKSB7aHR0cHM6Ly9mYXRlZ3JhbmRvcmRlci5mYW5kb20uY29tL3dpa2kvSHVudGluZ19RdWVzdHNfUGFydF9WSSN9IiwiZW5lbXkxaHAiOiIyODcyNSIsImVuZW15MWNsYXNzIjoiQXNzYXNzaW4iLCJlbmVteTFhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTFucGdhaW5tb2QiOiIwLjkiLCJlbmVteTJocCI6IjM0NjUwIiwiZW5lbXkyY2xhc3MiOiJBc3Nhc3NpbiIsImVuZW15MmF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15Mm5wZ2Fpbm1vZCI6IjAuOSIsImVuZW15M2hwIjoiMjg3MjUiLCJlbmVteTNjbGFzcyI6IkFzc2Fzc2luIiwiZW5lbXkzYXR0cmlidXRlIjoiTWFuIiwiZW5lbXkzbnBnYWlubW9kIjoiMC45IiwiZW5lbXk0aHAiOiI0MzM5NyIsImVuZW15NGNsYXNzIjoiQXNzYXNzaW4iLCJlbmVteTRhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTRucGdhaW5tb2QiOiIwLjkiLCJlbmVteTVocCI6IjYwODg1IiwiZW5lbXk1Y2xhc3MiOiJBc3Nhc3NpbiIsImVuZW15NWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15NW5wZ2Fpbm1vZCI6IjAuOSIsImVuZW15NmhwIjoiNDMzOTciLCJlbmVteTZjbGFzcyI6IkFzc2Fzc2luIiwiZW5lbXk2YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk2bnBnYWlubW9kIjoiMC45IiwiZW5lbXk3aHAiOiIxNDU1NjgiLCJlbmVteTdjbGFzcyI6IkJlcnNlcmtlciIsImVuZW15N2F0dHJpYnV0ZSI6IlNreSIsImVuZW15N25wZ2Fpbm1vZCI6IjAuOCIsImVuZW15OGhwIjoiMTA3MTM1IiwiZW5lbXk4Y2xhc3MiOiJCZXJzZXJrZXIiLCJlbmVteThhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteThucGdhaW5tb2QiOiIwLjgiLCJlbmVteTlocCI6IjE4MDM0NSIsImVuZW15OWNsYXNzIjoiQmVyc2Vya2VyIiwiZW5lbXk5YXR0cmlidXRlIjoiRWFydGgiLCJlbmVteTlucGdhaW5tb2QiOiIwLjgifSx7Im5hbWUiOiJMYW1wIG9mIEV2aWwgU2VhbGluZyBhbmQgTXlzdGljIEd1bnBvd2RlcjogRWZyZWV0IEh1bnQgUXVlc3QgKEh1bnRpbmcgUXVlc3QgUGFydCBWSSkge2h0dHBzOi8vZmF0ZWdyYW5kb3JkZXIuZmFuZG9tLmNvbS93aWtpL0h1bnRpbmdfUXVlc3RzX1BhcnRfVkkjfSIsImVuZW15MWhwIjoiMjA3MjciLCJlbmVteTFjbGFzcyI6IkFyY2hlciIsImVuZW15MWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15MW5wZ2Fpbm1vZCI6IjEiLCJlbmVteTJocCI6IjI2MzIxIiwiZW5lbXkyY2xhc3MiOiJBcmNoZXIiLCJlbmVteTJhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTJucGdhaW5tb2QiOiIxIiwiZW5lbXkzaHAiOiIyMDcyNyIsImVuZW15M2NsYXNzIjoiQXJjaGVyIiwiZW5lbXkzYXR0cmlidXRlIjoiTWFuIiwiZW5lbXkzbnBnYWlubW9kIjoiMSIsImVuZW15NGhwIjoiMzA2MTkiLCJlbmVteTRjbGFzcyI6IkFyY2hlciIsImVuZW15NGF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15NG5wZ2Fpbm1vZCI6IjEiLCJlbmVteTVocCI6IjMwNjE5IiwiZW5lbXk1Y2xhc3MiOiJBcmNoZXIiLCJlbmVteTVhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTVucGdhaW5tb2QiOiIxIiwiZW5lbXk2aHAiOiIzODc3MiIsImVuZW15NmNsYXNzIjoiQXJjaGVyIiwiZW5lbXk2YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk2bnBnYWlubW9kIjoiMSIsImVuZW15N2hwIjoiODgwNjAiLCJlbmVteTdjbGFzcyI6IkNhc3RlciIsImVuZW15N2F0dHJpYnV0ZSI6Ik1hbiIsImVuZW15N25wZ2Fpbm1vZCI6IjEuMiIsImVuZW15OGhwIjoiMTYzNzIxIiwiZW5lbXk4Y2xhc3MiOiJDYXN0ZXIiLCJlbmVteThhdHRyaWJ1dGUiOiJFYXJ0aCIsImVuZW15OG5wZ2Fpbm1vZCI6IjEuMiIsImVuZW15OWhwIjoiNDg4ODIiLCJlbmVteTljbGFzcyI6IkFzc2Fzc2luIiwiZW5lbXk5YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk5bnBnYWlubW9kIjoiMC45In0seyJuYW1lIjoiRXRlcm5hbCBHZWFyIGFuZCBTcGluYWwgRmx1aWQ6IEhlbHRlciBTa2VsdGVyIEh1bnQgUXVlc3QgKEh1bnRpbmcgUXVlc3QgUGFydCBWSSkge2h0dHBzOi8vZmF0ZWdyYW5kb3JkZXIuZmFuZG9tLmNvbS93aWtpL0h1bnRpbmdfUXVlc3RzX1BhcnRfVkkjfSIsImVuZW15MWhwIjoiMTY0MjAiLCJlbmVteTFjbGFzcyI6IlJpZGVyIiwiZW5lbXkxYXR0cmlidXRlIjoiTWFuIiwiZW5lbXkxbnBnYWlubW9kIjoiMS4xIiwiZW5lbXkyaHAiOiIzOTk1OSIsImVuZW15MmNsYXNzIjoiUmlkZXIiLCJlbmVteTJhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTJucGdhaW5tb2QiOiIxLjEiLCJlbmVteTNocCI6IjE5OTA0IiwiZW5lbXkzY2xhc3MiOiJDYXN0ZXIiLCJlbmVteTNhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTNucGdhaW5tb2QiOiIxLjIiLCJlbmVteTRocCI6IjM5OTU5IiwiZW5lbXk0Y2xhc3MiOiJSaWRlciIsImVuZW15NGF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15NG5wZ2Fpbm1vZCI6IjEuMSIsImVuZW15NWhwIjoiMzE5NDgiLCJlbmVteTVjbGFzcyI6IkNhc3RlciIsImVuZW15NWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15NW5wZ2Fpbm1vZCI6IjEuMiIsImVuZW15NmhwIjoiMzE5NDgiLCJlbmVteTZjbGFzcyI6IkNhc3RlciIsImVuZW15NmF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15Nm5wZ2Fpbm1vZCI6IjEuMiIsImVuZW15N2hwIjoiMTkzODQxIiwiZW5lbXk3Y2xhc3MiOiJSaWRlciIsImVuZW15N2F0dHJpYnV0ZSI6Ik1hbiIsImVuZW15N25wZ2Fpbm1vZCI6IjEuMSIsImVuZW15OGhwIjoiMzE5NDgiLCJlbmVteThjbGFzcyI6IkNhc3RlciIsImVuZW15OGF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15OG5wZ2Fpbm1vZCI6IjEuMiIsImVuZW15OWhwIjoiODYyNjMiLCJlbmVteTljbGFzcyI6IlJpZGVyIiwiZW5lbXk5YXR0cmlidXRlIjoiU2t5IiwiZW5lbXk5bnBnYWlubW9kIjoiMS4xIn0seyJuYW1lIjoiUGhvZW5peCBGZWF0aGVyczogQW1hem9uZXNzIEh1bnQgUXVlc3QgKEh1bnRpbmcgUXVlc3QgUGFydCBWSSkge2h0dHBzOi8vZmF0ZWdyYW5kb3JkZXIuZmFuZG9tLmNvbS93aWtpL0h1bnRpbmdfUXVlc3RzX1BhcnRfVkkjfSIsImVuZW15MWhwIjoiNDE5NDEiLCJlbmVteTFjbGFzcyI6IkFyY2hlciIsImVuZW15MWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15MW5wZ2Fpbm1vZCI6IjEiLCJlbmVteTJocCI6IjQ1NDI5IiwiZW5lbXkyY2xhc3MiOiJBcmNoZXIiLCJlbmVteTJhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTJucGdhaW5tb2QiOiIxIiwiZW5lbXkzaHAiOiI0MTk0MSIsImVuZW15M2NsYXNzIjoiQXJjaGVyIiwiZW5lbXkzYXR0cmlidXRlIjoiTWFuIiwiZW5lbXkzbnBnYWlubW9kIjoiMSIsImVuZW15NGhwIjoiNTMxOTEiLCJlbmVteTRjbGFzcyI6IkFyY2hlciIsImVuZW15NGF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15NG5wZ2Fpbm1vZCI6IjEiLCJlbmVteTVocCI6Ijg2NTAwIiwiZW5lbXk1Y2xhc3MiOiJBcmNoZXIiLCJlbmVteTVhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTVucGdhaW5tb2QiOiIxIiwiZW5lbXk2aHAiOiI1MzE5MSIsImVuZW15NmNsYXNzIjoiQXJjaGVyIiwiZW5lbXk2YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk2bnBnYWlubW9kIjoiMSIsImVuZW15N2hwIjoiODgwNjAiLCJlbmVteTdjbGFzcyI6IkFyY2hlciIsImVuZW15N2F0dHJpYnV0ZSI6IlNreSIsImVuZW15N25wZ2Fpbm1vZCI6IjEiLCJlbmVteThocCI6IjE2MDcxMyIsImVuZW15OGNsYXNzIjoiQXJjaGVyIiwiZW5lbXk4YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk4bnBnYWlubW9kIjoiMSIsImVuZW15OWhwIjoiNTUzMTgiLCJlbmVteTljbGFzcyI6IkFyY2hlciIsImVuZW15OWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15OW5wZ2Fpbm1vZCI6IjEifSx7Im5hbWUiOiJHcmVhdCBLbmlnaHQgTWVkYWw6IEtuaWdodCBFbmZvcmNlciBIdW50IFF1ZXN0IChIdW50aW5nIFF1ZXN0IFBhcnQgVkkpIHtodHRwczovL2ZhdGVncmFuZG9yZGVyLmZhbmRvbS5jb20vd2lraS9IdW50aW5nX1F1ZXN0c19QYXJ0X1ZJI30iLCJlbmVteTFocCI6IjIxMTMyIiwiZW5lbXkxY2xhc3MiOiJTYWJlciIsImVuZW15MWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15MW5wZ2Fpbm1vZCI6IjEiLCJlbmVteTJocCI6IjIxMTMyIiwiZW5lbXkyY2xhc3MiOiJTYWJlciIsImVuZW15MmF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15Mm5wZ2Fpbm1vZCI6IjEiLCJlbmVteTNocCI6IjI3Nzg4IiwiZW5lbXkzY2xhc3MiOiJTYWJlciIsImVuZW15M2F0dHJpYnV0ZSI6Ik1hbiIsImVuZW15M25wZ2Fpbm1vZCI6IjEiLCJlbmVteTRocCI6IjMzMzY0IiwiZW5lbXk0Y2xhc3MiOiJTYWJlciIsImVuZW15NGF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15NG5wZ2Fpbm1vZCI6IjEiLCJlbmVteTVocCI6IjQxMzcwIiwiZW5lbXk1Y2xhc3MiOiJTYWJlciIsImVuZW15NWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15NW5wZ2Fpbm1vZCI6IjEiLCJlbmVteTZocCI6IjMzMzY0IiwiZW5lbXk2Y2xhc3MiOiJTYWJlciIsImVuZW15NmF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15Nm5wZ2Fpbm1vZCI6IjEiLCJlbmVteTdocCI6IjkxNjU0IiwiZW5lbXk3Y2xhc3MiOiJMYW5jZXIiLCJlbmVteTdhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTducGdhaW5tb2QiOiIxIiwiZW5lbXk4aHAiOiIxODAyMzkiLCJlbmVteThjbGFzcyI6IkxhbmNlciIsImVuZW15OGF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15OG5wZ2Fpbm1vZCI6IjEiLCJlbmVteTlocCI6IjQ2OTU0IiwiZW5lbXk5Y2xhc3MiOiJTYWJlciIsImVuZW15OWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15OW5wZ2Fpbm1vZCI6IjEifSx7Im5hbWUiOiJFdmlsIEJvbmU6IFNrZWxldG9uIEh1bnQgUXVlc3QgKEh1bnRpbmcgUXVlc3QgUGFydCBWSSkge2h0dHBzOi8vZmF0ZWdyYW5kb3JkZXIuZmFuZG9tLmNvbS93aWtpL0h1bnRpbmdfUXVlc3RzX1BhcnRfVkkjfSIsImVuZW15MWhwIjoiMzU3NzkiLCJlbmVteTFjbGFzcyI6IkxhbmNlciIsImVuZW15MWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15MW5wZ2Fpbm1vZCI6IjEiLCJlbmVteTJocCI6IjM1MjU3IiwiZW5lbXkyY2xhc3MiOiJMYW5jZXIiLCJlbmVteTJhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTJucGdhaW5tb2QiOiIxIiwiZW5lbXkzaHAiOiIzNTc3OSIsImVuZW15M2NsYXNzIjoiTGFuY2VyIiwiZW5lbXkzYXR0cmlidXRlIjoiTWFuIiwiZW5lbXkzbnBnYWlubW9kIjoiMSIsImVuZW15NGhwIjoiNDk5MjIiLCJlbmVteTRjbGFzcyI6IkxhbmNlciIsImVuZW15NGF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15NG5wZ2Fpbm1vZCI6IjEiLCJlbmVteTVocCI6IjUxMzYzIiwiZW5lbXk1Y2xhc3MiOiJMYW5jZXIiLCJlbmVteTVhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTVucGdhaW5tb2QiOiIxIiwiZW5lbXk2aHAiOiI0OTkyMiIsImVuZW15NmNsYXNzIjoiTGFuY2VyIiwiZW5lbXk2YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk2bnBnYWlubW9kIjoiMSIsImVuZW15N2hwIjoiOTE2NTQiLCJlbmVteTdjbGFzcyI6IkxhbmNlciIsImVuZW15N2F0dHJpYnV0ZSI6IlNreSIsImVuZW15N25wZ2Fpbm1vZCI6IjEiLCJlbmVteThocCI6IjE5NDAwNSIsImVuZW15OGNsYXNzIjoiTGFuY2VyIiwiZW5lbXk4YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk4bnBnYWlubW9kIjoiMSIsImVuZW15OWhwIjoiNjY2MDQiLCJlbmVteTljbGFzcyI6IkxhbmNlciIsImVuZW15OWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15OW5wZ2Fpbm1vZCI6IjEifV0=

**Comment by gakiloroth** [comment]
nodes added
