### ISSUE TITLE
[BUG]: incorrect enemy listing for shinjuku 2-chome common node

### ISSUE THREAD

**Issue by Tomato-No-Mae** [gakiloroth/gakiloroth.github.io#15]
The common node default for shinjuku 2-chome lists the wave 3 enemy as a lancer when it should be an archer

1. Go to quest manager or battle simulator with shinjuku 2-chome selected
2. navigate to the third wave
3. third wave enemy listed as a lancer
4. In-game the enemy is an archer

this occurs in v2.09 which is, as far as i am aware the most recent release

**Comment by gakiloroth** [comment]
fixed with https://github.com/gakiloroth/gakiloroth.github.io/commit/0438a1869291f6b47e150383d3b12c3a677beed9

thanks for submitting the bug!
