### ISSUE TITLE
[BUG]: Website not showing information

### ISSUE THREAD

**Issue by NoOneofConsequencePrime** [gakiloroth/gakiloroth.github.io#17]
**Describe the bug**
The website suddenly is missing pages and information

**To Reproduce**
1. First time using, tried to export servant data after adding some stats
2. After which, the website auto reloaded, and began to bug out

**Expected behavior**
The website working properly?

**Screenshots**
![image](https://user-images.githubusercontent.com/74110977/159758275-a0bbb65f-d1ab-4bab-930a-f07b99abd7af.png)
![image](https://user-images.githubusercontent.com/74110977/159758304-5003a3c9-7491-4c39-bbc1-688eafa7769b.png)

**Platform(please complete the following information):**
-  Desktop
 - Windows 10
 - Chrome
 - v2.17

**Additional context**
Everything works fine if I open new incognito tab, could this be some issue with cache?

**Comment by gakiloroth** [comment]
Can you give more detailed steps? (ie what you clicked to cause the reload, perhaps what servants and stats you used if you can recreate this bug, etc.)

I tried adding some servants and exporting, but was unable to recreate the bug.

For now if you want to fix it without using incognito, you should be able to get it working by either clearing cache or clearing the local storage with F12 Dev Tools in Chrome :
![image](https://user-images.githubusercontent.com/9069768/159804591-3586ba47-4a79-4d26-9f25-24e9a19af92b.png)

**Comment by NoOneofConsequencePrime** [comment]
Manually clearing cache worked, thank you.

As for detailed steps, my memories are bit vague, and that was the first time I ever used the website. Here's what I can recall:

Chose "berserker" for class
Chose "musashi" for servant
Max fou
NP Gain up 60%
Arts Up 60%
MLB selected
then exported servant data?

It's probably not these exact steps, but I think that was somewhat close to what I did.

**Comment by gakiloroth** [comment]
Hm, I'm unable to recreate with these steps so I'll close it for now, but if you manage to re-create it (ideally consistently) please re-open with steps if you want.
