### ISSUE TITLE
[BUG]: The calculator reloads when pressing enter on any values

### ISSUE THREAD

**Issue by abhy-kumar** [gakiloroth/gakiloroth.github.io#2]
**Describe the bug**
The calculator reloads when pressing enter on any values, which wipes all of the previously entered content. From a QoL POV, this is a bad thing.

**To Reproduce**
Just press [Enter] after entering any value

**Expected behavior**
The page should just not reload on key press.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 69.0.1
 - Version: 69.0.1

**Comment by gakiloroth** [comment]
Just making sure, is this only on the servant tab or all 3 tabs?

**Comment by abhy-kumar** [comment]
yeah, only on the initial servant manager tab.

**Comment by gakiloroth** [comment]
i pushed a fix, let me know if the behavior is fixed, and thanks for letting me know!

**Comment by abhy-kumar** [comment]
Thanks. The behaviour is fixed.
