### ISSUE TITLE
[BUG]: ScathachFest 2020 Rotation 2 90 Ticket node common node error

### ISSUE THREAD

**Issue by The-Intelligent-One** [gakiloroth/gakiloroth.github.io#23]
The "ScathachFest 2020 Rotation 2 90 Ticket node" in the common nodes has an error in it: the HP of enemy 9 has an extra 0 at the end, making it 10 times as much as it should be

**Comment by gakiloroth** [comment]
Thanks for letting me know, going forward I plan to use Atlas Academy API to build these so hopefully typos don't happen

Should be fixed by [c5c4629bca3488f1eccb467d1d3be47e4cecdfee](https://github.com/gakiloroth/gakiloroth.github.io/commit/c5c4629bca3488f1eccb467d1d3be47e4cecdfee)
