### ISSUE TITLE
[NODES] Node name/Usage/Etc.

### ISSUE THREAD

**Issue by Shinayaya** [gakiloroth/gakiloroth.github.io#29]
**Reason for adding**
90+ node that drops all currency (Lotto, Bronze, Silver, Gold) in the 2021 Christmas lotto event.

**Name of the node and Wiki / Atlas Academy Link**
Christmas 2021 90+ - https://apps.atlasacademy.io/db/JP/quest/94064409/1

W3sibmFtZSI6IkNocmlzdG1hcyAyMDIxIiwiZW5lbXkxaHAiOiI0MDYyNSIsImVuZW15MWNsYXNzIjoiQXNzYXNzaW4iLCJlbmVteTFhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTFucGdhaW5tb2QiOiIwLjkiLCJlbmVteTJocCI6IjUwODQ0IiwiZW5lbXkyY2xhc3MiOiJBc3Nhc3NpbiIsImVuZW15MmF0dHJpYnV0ZSI6IlNreSIsImVuZW15Mm5wZ2Fpbm1vZCI6IjAuOSIsImVuZW15M2hwIjoiNDA2MjUiLCJlbmVteTNjbGFzcyI6IkFzc2Fzc2luIiwiZW5lbXkzYXR0cmlidXRlIjoiU2t5IiwiZW5lbXkzbnBnYWlubW9kIjoiMC45IiwiZW5lbXk0aHAiOiIwIiwiZW5lbXk0Y2xhc3MiOiJTYWJlciIsImVuZW15NGF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15NG5wZ2Fpbm1vZCI6IjEiLCJlbmVteTVocCI6IjE1ODMyMyIsImVuZW15NWNsYXNzIjoiQXNzYXNzaW4iLCJlbmVteTVhdHRyaWJ1dGUiOiJFYXJ0aCIsImVuZW15NW5wZ2Fpbm1vZCI6IjAuOSIsImVuZW15NmhwIjoiMCIsImVuZW15NmNsYXNzIjoiU2FiZXIiLCJlbmVteTZhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTZucGdhaW5tb2QiOiIxIiwiZW5lbXk3aHAiOiIwIiwiZW5lbXk3Y2xhc3MiOiJTYWJlciIsImVuZW15N2F0dHJpYnV0ZSI6Ik1hbiIsImVuZW15N25wZ2Fpbm1vZCI6IjEiLCJlbmVteThocCI6IjIxMjI1NiIsImVuZW15OGNsYXNzIjoiQXNzYXNzaW4iLCJlbmVteThhdHRyaWJ1dGUiOiJFYXJ0aCIsImVuZW15OG5wZ2Fpbm1vZCI6IjAuOSIsImVuZW15OWhwIjoiMCIsImVuZW15OWNsYXNzIjoiU2FiZXIiLCJlbmVteTlhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTlucGdhaW5tb2QiOiIxIn0seyJuYW1lIjoiVmFsZW50aW5lIDIwMjMgOTArIiwiZW5lbXkxaHAiOiIwIiwiZW5lbXkxY2xhc3MiOiJTYWJlciIsImVuZW15MWF0dHJpYnV0ZSI6Ik1hbiIsImVuZW15MW5wZ2Fpbm1vZCI6IjEiLCJlbmVteTJocCI6IjY4NTExIiwiZW5lbXkyY2xhc3MiOiJMYW5jZXIiLCJlbmVteTJhdHRyaWJ1dGUiOiJFYXJ0aCIsImVuZW15Mm5wZ2Fpbm1vZCI6IjEiLCJlbmVteTNocCI6IjAiLCJlbmVteTNjbGFzcyI6IlNhYmVyIiwiZW5lbXkzYXR0cmlidXRlIjoiTWFuIiwiZW5lbXkzbnBnYWlubW9kIjoiMSIsImVuZW15NGhwIjoiMCIsImVuZW15NGNsYXNzIjoiU2FiZXIiLCJlbmVteTRhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTRucGdhaW5tb2QiOiIxIiwiZW5lbXk1aHAiOiIxNTY5ODgiLCJlbmVteTVjbGFzcyI6IkxhbmNlciIsImVuZW15NWF0dHJpYnV0ZSI6IkVhcnRoIiwiZW5lbXk1bnBnYWlubW9kIjoiMSIsImVuZW15NmhwIjoiMCIsImVuZW15NmNsYXNzIjoiU2FiZXIiLCJlbmVteTZhdHRyaWJ1dGUiOiJNYW4iLCJlbmVteTZucGdhaW5tb2QiOiIxIiwiZW5lbXk3aHAiOiIxOTM1NDUiLCJlbmVteTdjbGFzcyI6IkxhbmNlciIsImVuZW15N2F0dHJpYnV0ZSI6IlNreSIsImVuZW15N25wZ2Fpbm1vZCI6IjEiLCJlbmVteThocCI6IjAiLCJlbmVteThjbGFzcyI6IlNhYmVyIiwiZW5lbXk4YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk4bnBnYWlubW9kIjoiMSIsImVuZW15OWhwIjoiODg4MjAiLCJlbmVteTljbGFzcyI6IkxhbmNlciIsImVuZW15OWF0dHJpYnV0ZSI6IkVhcnRoIiwiZW5lbXk5bnBnYWlubW9kIjoiMSJ9LHsibmFtZSI6IlF1ZXN0IE5hbWUiLCJlbmVteTFocCI6IjMyOTQ2IiwiZW5lbXkxY2xhc3MiOiJCZXJzZXJrZXIiLCJlbmVteTFhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTFucGdhaW5tb2QiOiIwLjgiLCJlbmVteTJocCI6IjI2NzE4IiwiZW5lbXkyY2xhc3MiOiJCZXJzZXJrZXIiLCJlbmVteTJhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTJucGdhaW5tb2QiOiIwLjgiLCJlbmVteTNocCI6IjI2NzE4IiwiZW5lbXkzY2xhc3MiOiJCZXJzZXJrZXIiLCJlbmVteTNhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTNucGdhaW5tb2QiOiIwLjgiLCJlbmVteTRocCI6IjQ1MjgxIiwiZW5lbXk0Y2xhc3MiOiJCZXJzZXJrZXIiLCJlbmVteTRhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTRucGdhaW5tb2QiOiIwLjgiLCJlbmVteTVocCI6IjUzMzIwIiwiZW5lbXk1Y2xhc3MiOiJCZXJzZXJrZXIiLCJlbmVteTVhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTVucGdhaW5tb2QiOiIwLjgiLCJlbmVteTZocCI6IjEzMDE3NCIsImVuZW15NmNsYXNzIjoiQmVyc2Vya2VyIiwiZW5lbXk2YXR0cmlidXRlIjoiU2t5IiwiZW5lbXk2bnBnYWlubW9kIjoiMC44IiwiZW5lbXk3aHAiOiI2NTQ2NCIsImVuZW15N2NsYXNzIjoiQmVyc2Vya2VyIiwiZW5lbXk3YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk3bnBnYWlubW9kIjoiMC44IiwiZW5lbXk4aHAiOiIxMDA5MjYiLCJlbmVteThjbGFzcyI6IlJ1bGVyIiwiZW5lbXk4YXR0cmlidXRlIjoiU2t5IiwiZW5lbXk4bnBnYWlubW9kIjoiMSIsImVuZW15OWhwIjoiODU0MDUiLCJlbmVteTljbGFzcyI6IlJ1bGVyIiwiZW5lbXk5YXR0cmlidXRlIjoiU2t5IiwiZW5lbXk5bnBnYWlubW9kIjoiMSJ9LHsibmFtZSI6IlFQIERhaWx5IChFeHRyZW1lKSAiLCJlbmVteTFocCI6IjIzNzU1IiwiZW5lbXkxY2xhc3MiOiJDYXN0ZXIiLCJlbmVteTFhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTFucGdhaW5tb2QiOiIxLjIiLCJlbmVteTJocCI6IjI0NDgzIiwiZW5lbXkyY2xhc3MiOiJDYXN0ZXIiLCJlbmVteTJhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTJucGdhaW5tb2QiOiIxLjIiLCJlbmVteTNocCI6IjIzMDI3IiwiZW5lbXkzY2xhc3MiOiJDYXN0ZXIiLCJlbmVteTNhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTNucGdhaW5tb2QiOiIxLjIiLCJlbmVteTRocCI6IjMwMjUyIiwiZW5lbXk0Y2xhc3MiOiJDYXN0ZXIiLCJlbmVteTRhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTRucGdhaW5tb2QiOiIxLjIiLCJlbmVteTVocCI6IjMxOTk5IiwiZW5lbXk1Y2xhc3MiOiJDYXN0ZXIiLCJlbmVteTVhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTVucGdhaW5tb2QiOiIxLjIiLCJlbmVteTZocCI6IjMxMTI1IiwiZW5lbXk2Y2xhc3MiOiJDYXN0ZXIiLCJlbmVteTZhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteTZucGdhaW5tb2QiOiIxLjIiLCJlbmVteTdocCI6IjAiLCJlbmVteTdjbGFzcyI6IlNhYmVyIiwiZW5lbXk3YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk3bnBnYWlubW9kIjoiMSIsImVuZW15OGhwIjoiMTMyOTMyIiwiZW5lbXk4Y2xhc3MiOiJDYXN0ZXIiLCJlbmVteThhdHRyaWJ1dGUiOiJTa3kiLCJlbmVteThucGdhaW5tb2QiOiIxLjIiLCJlbmVteTlocCI6IjAiLCJlbmVteTljbGFzcyI6IlNhYmVyIiwiZW5lbXk5YXR0cmlidXRlIjoiTWFuIiwiZW5lbXk5bnBnYWlubW9kIjoiMSJ9XQ==

**Comment by gakiloroth** [comment]
Thanks! You only have to do the quest code **OR** the Atlas API link, not both - but it doesn't hurt.

added in 6d32fff17016f950fbf4e0795ef97f67cc977cbb
