### ISSUE TITLE
[FEATURE REQUEST]: Add Beast attribute in the Quests Manager tab

### ISSUE THREAD

**Issue by Shinayaya** [gakiloroth/gakiloroth.github.io#32]
**Is your feature request related to a problem? Please describe.**
The Quests Manager tab of the site has attribute drop-down menus, These only let me select one of the four "common" attributes (earth, sky, man and star). There is no Beast option.

**Describe the solution you'd like**
Add Beast attribute to the attribute drop-down menu in the Quests Manager tab.

**Describe alternatives you've considered**
I have no alternative solutions. I hope this is easy to fix.

**Additional context**
I'm trying to add all the 90+ and 90++ nodes from Morgan Fest to the common nodes, but I just stumbled upon this node: https://apps.atlasacademy.io/db/JP/quest/94077813/1/stage-3
On wave 3, it has 2 beast attribute enemies.

**Comment by gakiloroth** [comment]
fixed in 21020fdbb865cbbe5314bacbe179c3d08bfd1627
