### ISSUE TITLE
[BUG]: Servant Power Mod Miscalculation

### ISSUE THREAD

**Issue by TCZapper** [gakiloroth/gakiloroth.github.io#5]
**Describe the bug**
If I set a Power Mod in the Servants Manager to 100%, it increases damage by 1000% in the Battle Simulator.

**To Reproduce**
1. Add NP5 Para as a servant with only a 100% Power Mod buff
2. Setup quest with earth assassins
3. Run battle simulator

Damage is reported as 148k min, 11x the 13k damage reported without the power mod.

**Expected behavior**
Damage should be 26k (2x non-power mod damage)

**Platform(please complete the following information):**
-  Desktop/Mobile: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 76.0.1

**Comment by gakiloroth** [comment]
I see you testing that gilfest! thanks for catching this - a silly bug I caught for other things but not servant powermod.
